djangocms_translations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import logging

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.db import IntegrityError, models, transaction
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin
from cms.models.fields import PageField, PlaceholderField
from cms.utils.plugins import copy_plugins_to_placeholder

from djangocms_transfer.exporter import get_page_export_data
from djangocms_transfer.importer import import_plugins_to_page
from djangocms_transfer.utils import get_plugin_class
from extended_choices import Choices

from .providers import TRANSLATION_PROVIDERS, SupertextTranslationProvider
from .utils import get_plugin_form


logger = logging.getLogger('djangocms_translations')


def _get_placeholder_slot(archived_placeholder):
    return archived_placeholder.slot


class TranslationRequest(models.Model):
    STATES = Choices(
        ('DRAFT', 'draft', _('Draft')),
        ('OPEN', 'open', _('Open')),
        ('PENDING_QUOTE', 'pending_quote', _('Pending quote from provider')),
        ('PENDING_APPROVAL', 'pending_approval', _('Pending approval of quote')),
        ('READY_FOR_SUBMISSION', 'ready_for_submission', _('Pending submission to translation provider')),
        ('IN_TRANSLATION', 'in_translation', _('In translation')),
        ('IMPORT_STARTED', 'import_started', _('Import started')),
        ('IMPORT_FAILED', 'import_failed', _('Import failed')),
        ('IMPORTED', 'imported', _('Imported')),
        ('CANCELLED', 'cancelled', _('Cancelled')),
    )

    PROVIDERS = Choices(
        ('SUPERTEXT', SupertextTranslationProvider.__name__, _('Supertext')),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    state = models.CharField(choices=STATES, default=STATES.DRAFT, max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)
    date_submitted = models.DateTimeField(blank=True, null=True)
    date_received = models.DateTimeField(blank=True, null=True)
    date_imported = models.DateTimeField(blank=True, null=True)
    source_language = models.CharField(max_length=10, choices=settings.LANGUAGES)
    target_language = models.CharField(max_length=10, choices=settings.LANGUAGES)
    provider_backend = models.CharField(max_length=100, choices=PROVIDERS)
    provider_order_name = models.CharField(max_length=255, blank=True)
    provider_options = JSONField(default=dict, blank=True)
    export_content = JSONField(default=dict, blank=True)
    request_content = JSONField(default=dict, blank=True)
    selected_quote = models.ForeignKey('TranslationQuote', blank=True, null=True, on_delete=models.CASCADE)

    @property
    def status(self):
        return self.STATES.for_value(self.state).display

    @property
    def provider(self):
        if not self._provider and self.provider_backend:
            self._provider = TRANSLATION_PROVIDERS.get(self.provider_backend)(self)
        return self._provider
    _provider = None

    def set_status(self, status, commit=True):
        assert status in self.STATES.values, _('Invalid status')
        self.state = status

        if commit:
            self.save(update_fields=('state',))
        return not status == self.STATES.IMPORT_FAILED

    def set_provider_order_name(self, source_page):
        initial_page_title = source_page.get_page_title(self.source_language)
        request_item_count = self.items.count()

        if request_item_count > 1:
            bulk_text = _(' - {} pages').format(request_item_count)
        else:
            bulk_text = ''
        self.provider_order_name = _('Order #{} - {}{}').format(self.pk, initial_page_title, bulk_text)
        self.save(update_fields=('provider_order_name',))

    def set_content_from_cms(self):
        export_content = []
        for item in self.items.all():
            export_content.extend(item.get_export_data(self.source_language))

        self.export_content = json.dumps(export_content, cls=DjangoJSONEncoder)
        self.save(update_fields=('export_content',))
        self.set_status(self.STATES.OPEN)

    def set_provider_options(self, **kwargs):
        self.provider_options = self.provider.get_provider_options(**kwargs)
        self.save(update_fields=('provider_options',))

    def get_quote_from_provider(self):
        self.set_status(self.STATES.PENDING_QUOTE)

        provider_quote = self.provider.get_quote()

        currency = provider_quote['Currency']
        date_received = timezone.now()
        quotes = []

        for option in provider_quote['Options']:
            order_type_id = option['OrderTypeId']
            name = '{} ({})'.format(option['Name'], option['ShortDescription'])
            description = option['Description']

            for delivery_option in option['DeliveryOptions']:
                quote = self.quotes.create(
                    provider_options={
                        'OrderTypeId': order_type_id,
                        'DeliveryId': delivery_option['DeliveryId'],
                    },
                    name=name,
                    description=description,
                    delivery_date=delivery_option['DeliveryDate'],
                    delivery_date_name=delivery_option['Name'],
                    price_currency=currency,
                    price_amount=delivery_option['Price'] or 0,
                    date_received=date_received,
                )
                quotes.append(quote)

        self.set_status(self.STATES.PENDING_APPROVAL)

    def set_request_content(self):
        self.request_content = self.provider.get_export_data()
        self.save(update_fields=('request_content',))

    def submit_request(self):
        response = self.provider.send_request()
        self.set_status(self.STATES.IN_TRANSLATION)
        return response

    def check_status(self):
        assert hasattr(self, 'order'), _('Cannot check status if there is no order.')
        status = self.provider.check_status()
        self.order.state = status['Status'].lower()
        # TODO: which states are available?
        # on success, update the requests status as well
        self.order.save(update_fields=('state',))

    def import_response(self, raw_data):
        import_state = TranslationImport.objects.create(request=self)
        self.set_status(self.STATES.IMPORT_STARTED)
        self.order.response_content = raw_data.decode('utf-8')
        self.order.save(update_fields=('response_content',))

        try:
            import_data = self.provider.get_import_data()
        except ValueError:
            message = _('Received invalid data from {}.').format(self.provider_backend)
            logger.exception(message)
            import_state.set_error_message(message)
            return self.set_status(self.STATES.IMPORT_FAILED)

        id_item_mapping = self.items.in_bulk()
        import_error = False
        for translation_request_item_pk, placeholders in import_data.items():
            translation_request_item = id_item_mapping[translation_request_item_pk]
            try:
                import_plugins_to_page(
                    placeholders=placeholders,
                    page=translation_request_item.target_cms_page,
                    language=self.target_language
                )
            except (IntegrityError, ObjectDoesNotExist):
                self._set_import_archive()
                message = _('Failed to import plugins from {}.').format(self.provider_backend)
                logger.exception(message)
                import_state.set_error_message(message)
                import_error = True

        if import_error:
            # FIXME: this or all-or-nothing (atomic)?
            return self.set_status(self.STATES.IMPORT_FAILED)

        self.set_status(self.STATES.IMPORTED, commit=False)
        self.date_imported = timezone.now()
        self.save(update_fields=('date_imported', 'state'))
        import_state.state = import_state.STATES.IMPORTED
        import_state.save(update_fields=('state', ))
        return True

    def can_import_from_archive(self):
        if self.state == self.STATES.IMPORT_FAILED:
            return self.archived_placeholders.exists()
        return False

    @transaction.atomic
    def _import_from_archive(self):
        plugins_by_placeholder = {
            pl.slot: pl.get_plugins()
            for pl in self.archived_placeholders.all()
        }
        for translation_request_item in self.items.select_related('target_cms_page'):
            page_placeholders = (
                translation_request_item
                .target_cms_page
                .placeholders
                .filter(slot__in=plugins_by_placeholder)
            )

            for placeholder in page_placeholders:
                plugins = plugins_by_placeholder[placeholder.slot]
                copy_plugins_to_placeholder(
                    plugins=plugins,
                    placeholder=placeholder,
                    language=self.target_language,
                )

        self.set_status(self.STATES.IMPORTED, commit=False)
        self.date_imported = timezone.now()
        self.save(update_fields=('date_imported', 'state'))

    @transaction.atomic
    def _set_import_archive(self):
        import_data = self.provider.get_import_data()
        id_item_mapping = self.items.in_bulk()

        for translation_request_item_pk, placeholders in import_data:
            translation_request_item = id_item_mapping[translation_request_item_pk]
            page_placeholders = translation_request_item.source_cms_page.get_declared_placeholders()

            plugins_by_placeholder = {

djangocms_translations/templates/djangocms_translations/adjust_import_data.html
{% load cms_tags cms_js_tags i18n sekizai_tags %}
<!DOCTYPE html>
<html class="cms-overflow">
<head>
    <meta charset="UTF-8">
    <title>Adjust import data</title>
    {% render_block "css" %}
</head>
<body>
    {% cms_toolbar %}
    {% render_block "js" %}
    {% language cms_toolbar.toolbar_language %}
        {{ toolbar.structure_renderer.render }}
    {% endlanguage %}
    <script type="text/javascript">
        (function () {
            var xPath = function (expression) {
                var results = [];
                var xPathResult = document.evaluate(expression, document, null, XPathResult.ANY_TYPE, null);

                var result = xPathResult.iterateNext();

                while (result) {
                    results.push(result);
                    result = xPathResult.iterateNext();
                }

                return results;
            }

            try {
                var $ = CMS.$;
                $(xPath('//*[contains(text(), "<Empty>")]')).closest('.cms-dragitem').css('background', '#ff9696')
            } catch(e) {
                // xpath not supported
            }
        })();
    </script>
</body>
</html>

djangocms_translations/templates/djangocms_translations/base.html
{% extends "admin/base_site.html" %}
{% load i18n cms_tags %}

{% block extrahead %}
	{{ block.super }}
	{{ form.media }}
{% endblock %}

{% block content %}
{% endblock content %}

djangocms_translations/templates/djangocms_translations/choose_quote.html
{% extends "djangocms_translations/base.html" %}
{% load i18n cms_tags %}

{% block content %}
    <h1>Choose quote</h1>
    <form id="choose-quote" action="" method="post" class="frm">
        {% csrf_token %}
        <fieldset class="frm-horizontal">
            {{ form.as_p }}
        </fieldset>
        <input type="submit" value="Submit" />
    </form>
    <script type="text/javascript">
        document.querySelector('#choose-quote').addEventListener('submit', function (e) {
            document.querySelector('#choose-quote [type=submit]').setAttribute('disabled', true);
        });
    </script>
{% endblock content %}

djangocms_translations/templates/djangocms_translations/create_request.html
{% extends "djangocms_translations/base.html" %}
{% load i18n cms_tags %}

{% block content %}
	<h1>Add a new translation request</h1>
	<form action="" method="post" class="frm">
	    {% csrf_token %}
		{% for field in form.hidden_fields %}
			<p>{{ field }}</p>
		{% endfor %}

        {{ form.non_field_errors }}

	    <fieldset class="frm-horizontal">
			{% for field in form.visible_fields %}
				<p>
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </p>
			{% endfor %}
	    </fieldset>
        <input type="submit" value="Submit" />
	</form>
{% endblock content %}

djangocms_translations/templates/djangocms_translations/import_confirmation.html
{% extends "admin/delete_confirmation.html" %}
{% load i18n admin_urls static %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'admin/js/cancel.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    &rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
    &rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst|escape }}</a>
    &rsaquo; <a href="{% url opts|admin_urlname:'change' object.pk|admin_urlquote %}">{{ object|truncatewords:"18" }}</a>
    &rsaquo; {% trans 'Import from archive' %}
    </div>
{% endblock %}

{% block content %}
    <p>{% blocktrans %}Are you sure you want to import plugins from the translation archive?{% endblocktrans %}</p>
    <form action="." method="post">
        {% csrf_token %}
        <div>
            <input type="hidden" name="action" value="import_from_archive">
            <input type="hidden" name="post" value="yes">
            <a href="#" onclick="window.history.back(); return false;" class="button cancel-link">{% trans "No, take me back" %}</a>
            <input type="submit" value="{% trans 'Yes, I&#39;m sure' %}">
        </div>
    </form>
{% endblock %}

djangocms_translations/templates/djangocms_translations/log.html
{% extends "djangocms_translations/base.html" %}
{% load i18n admin_urls cms_tags %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    &rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
    &rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst|escape }}</a>
    &rsaquo; <a href="{% url opts|admin_urlname:'change' object.pk|admin_urlquote %}">{{ object|truncatewords:"18" }}</a>
    &rsaquo; {% trans 'Error log' %}
    </div>
{% endblock %}

{% block content %}
<div class="results">
    <table id="result_list">
        <thead>
            <tr>
                <th>{% trans 'Time' %}</th>
                <th>{% trans 'Status' %}</th>
                <th>{% trans 'Message' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object.imports.all %}
            <tr class="{% cycle 'row1' 'row2' %}">
                <td>{{ item.date_created }}</td>
                <td>{{ item.get_state_display }}</td>
                <td>{{ item.message }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">{% trans 'No imports logged' %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

djangocms_translations/templates/djangocms_translations/pages_sent.html
{% extends "djangocms_translations/base.html" %}
{% load i18n admin_urls cms_tags %}

{% block extrahead %}{{ block.super }}
<script>
    function closeSideframe() {
        try {
            window.top.CMS.$('.cms-sideframe-close').trigger('click.cms.sideframe');
        } catch(e) {}
    }
</script>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    &rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
    &rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst|escape }}</a>
    &rsaquo; <a href="{% url opts|admin_urlname:'change' object.pk|admin_urlquote %}">{{ object|truncatewords:"18" }}</a>
    &rsaquo; {% trans 'Pages sent' %}
    </div>
{% endblock %}

{% block content %}
<div class="results">
    <table id="result_list">
        <thead>
            <tr>
                <th>{% trans 'Title' %}</th>
                <th>{% trans 'Slug' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object.items.all %}
            <tr class="{% cycle 'row1' 'row2' %}">
                <td><a target="_top" onclick="closeSideframe()" href="{% page_url item.source_cms_page object.source_language %}">{{ item.source_cms_page_title }}</a></td>
                <td>{% page_url item.source_cms_page object.source_language %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

djangocms_translations/templates/djangocms_translations/status_detail.html
{% extends "djangocms_translations/base.html" %}
{% load i18n cms_tags %}

{% block content %}
	<h1>Status</h1>
	<table border="1">
		<tr>
			<th>{% trans 'Status' %}</th>
			<td>{{ object.status }}</td>
		</tr>
	</table>
	<form action="{% url 'admin:translation-request-check-status' object.pk %}" method="post">
		{% csrf_token %}
		<button type="submit" value="">Check status</button>

	</form>
{% endblock content %}